name: my_vpn_app
description: 喵脸 VPN 
version: 1.0.0+104

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  device_info_plus: ^10.1.0
  android_id: ^0.4.0
  uuid: ^4.4.0
  package_info_plus: ^8.0.0
  flutter_secure_storage: ^9.0.0
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # 1. 自动切图生成图标的依赖库
  flutter_launcher_icons: "^0.13.1"

# 2. 图标生成专属规则配置
flutter_launcher_icons:
  android: "ic_launcher"               # 自动绑定安卓底层的 launcher 图标名
  ios: true                            # 同时为 iOS 端切图生成
  image_path: "assets/app_icon.png"    # 请将准备好的 1024x1024 图标命名为这个路径
  min_sdk_android: 26                  # 与你刚配置的 VPN 底层 SDK 26 保持完美一致

flutter:
  uses-material-design: true

  # 3. 开启 assets 资源加载声明
  # 这里声明的是"文件夹"，该文件夹下所有文件都会被自动打包进App，
  # 不需要每加一张图就手动加一行。把图标文件放进 assets/ 目录下即可。
  assets:
    - assets/